# Generated by Django 4.1.5 on 2023-01-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Years_averageSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('average_salary', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Years_averageSalaryManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField()),
                ('average_salaryManager', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Years_vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField()),
                ('all_vacancies', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Years_vacanciesManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField()),
                ('vacancies_manager', models.IntegerField()),
            ],
        ),
    ]
