# Generated by Django 4.1.5 on 2023-01-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_app', '0002_rename_year_years_averagesalary_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='key_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('skill', models.CharField(max_length=50)),
            ],
        ),
    ]
