# Generated by Django 4.1.5 on 2023-01-14 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp_app', '0003_key_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='key_skills',
            new_name='key_skill',
        ),
    ]
